name: $(Build.SourceVersion)
jobs:
- job: Linux
  timeoutInMinutes: 0
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: .ci/esy-build-steps.yml

- job: MacOS
  timeoutInMinutes: 0
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - template: .ci/esy-build-steps.yml

# - job: Windows
#   timeoutInMinutes: 0
#   pool:
#     vmImage: 'vs2017-win2016'
#   steps:
#   - template: esy-build-steps.yml

- job: Release
  displayName: Release
  dependsOn:
      - Linux
      - MacOS
      - Windows
  condition: succeeded()
  timeoutInMinutes: 0
  pool:
     vmImage: ubuntu-16.04
  steps:
    - task: PublishBuildArtifacts@1
      displayName: 'Release Package'
      inputs:
          PathtoPublish: '.'
          ArtifactName: npm-package
